# Generated by Django 4.2.6 on 2023-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('proimg', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
